### ISSUE TITLE
Page stuck in loading state

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/jediswap-v2-interface#126]
### Description
Page is perpetually stuck in loading state unless you connect wallet and switch to testnet and reloads the page.

https://testnet.e2.jediswap.xyz/#/swap
<img width="575" alt="image" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/4688513/4f17263f-8ce8-40a8-b750-4145a5710634">

**Comment by vnaysngh-mudrex** [comment]
fixing this rightaway

**Comment by vnaysngh-mudrex** [comment]
done and deployed
