### ISSUE TITLE
Correct the support link in the error screen

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/jediswap-v2-interface#130]
### Description

Whenever there is an error in the app it opens an error screen.
In the error screen there is a button for "get support"
It is taking to wrong Discord. The correct link should be https://discord.gg/jediswap

<img width="562" alt="image" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/4688513/47a38ab0-69f7-46f9-9697-f11a49ccce8b">

**Comment by vnaysngh-mudrex** [comment]
done and deployed
