### ISSUE TITLE
Deactivate remove liquidity button on a closed position 

### ISSUE THREAD

**Issue by princearoragithub** [jediswaplabs/jediswap-v2-interface#135]
### Description

<img width="935" alt="Screenshot 2024-02-06 at 7 14 23 PM" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/77785932/b410a3aa-41b2-4e67-be8a-5012ff799095">

**Comment by rohitgoyal** [comment]
Hide remove liquidity button for closed positions

**Comment by rohitgoyal** [comment]
We can merge it to production.

**Comment by vnaysngh-mudrex** [comment]
this is merged to prod and deployed
