### ISSUE TITLE
Remove unnecessary githubusercontent fetch request

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/jediswap-v2-interface#137]
### Description

Client is calling unnecessary raw github urls for fetching some logos. 
Remove these requests.

https://raw.githubusercontent.com/Uniswap/assets/master/blockchains/ethereum/assets/0x012d537dc323c439dc65c976fad242d5610d27cfb5f31689a0a319b8be7f3d56/logo.png

**Comment by rohitgoyal** [comment]
Need to observe again. 
@vnaysngh-mudrex mentioned he resolved it.

**Comment by vnaysngh-mudrex** [comment]
Can we close this @rohitgoyal
