### ISSUE TITLE
Insufficient liquidity whenever I am using Braavos for any of the pair

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/jediswap-v2-interface#138]
### Description

The error coming is the same as it was coming in the other error I shared about insufficient liquidity.

Error
`{
    "jsonrpc": "2.0",
    "error": {
        "code": 40,
        "message": "Contract error",
        "data": {
            "revert_error": "Error in the called contract (0x0767062eca7d10a7f0fc891ec33eac2383a1b5dd928444d3d4474032d990a11b):\nError at pc=0:10:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:228)\nUnknown location (pc=0:214)\n\nError in the called contract (0x0767062eca7d10a7f0fc891ec33eac2383a1b5dd928444d3d4474032d990a11b):\nError at pc=0:8771:\nAn ASSERT_EQ instruction failed: 6:6 != 6:7."
        }
    },
    "id": 0
}`

Payload
`{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "starknet_simulateTransactions",
    "params": {
        "block_id": {
            "block_number": 946383
        },
        "transactions": [
            {
                "type": "INVOKE",
                "sender_address": "0x767062eca7d10a7f0fc891ec33eac2383a1b5dd928444d3d4474032d990a11b",
                "calldata": [
                    "0x1",
                    "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
                    "0x219209e083275171774dab1df80982e9df2096516f06319c5c6d71ae0a8480c",
                    "0x3",
                    "0x38eaefeb9950c40a0a85f35378055e4c9739a1eb20e87e122ff66b4223d65ab",
                    "0x0",
                    "0x1"
                ],
                "version": "0x1",
                "signature": [
                    "0x60101f1262b067c3ddf5339dcca3e83bef78c951c7d34ed26b1c1068177b958",
                    "0x5f54ceafa740f7056447e9cc76ff0f2a9d5679b5ba27b96ab0e5c15ed759c4f"
                ],
                "nonce": "0x4",
                "max_fee": "0x0"
            },
            {
                "type": "INVOKE",
                "sender_address": "0x767062eca7d10a7f0fc891ec33eac2383a1b5dd928444d3d4474032d990a11b",
                "calldata": [
                    "0x1",
                    "0x38eaefeb9950c40a0a85f35378055e4c9739a1eb20e87e122ff66b4223d65ab",
                    "0x8b15073164d9faa52b205fa2eecbf6004827f35a3730e91da3990d533ccfe8",
                    "0xb",
                    "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
                    "0x3e85bfbb8e2a42b7bead9e88e9a1b19dbccf661471061807292120462396ec9",
                    "0xbb8",
                    "0x767062eca7d10a7f0fc891ec33eac2383a1b5dd928444d3d4474032d990a11b",
                    "0x65c33d4f",
                    "0x16345785d8a0000",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0"
                ],
                "version": "0x1",
                "signature": [
                    "0x60101f1262b067c3ddf5339dcca3e83bef78c951c7d34ed26b1c1068177b958",
                    "0x5f54ceafa740f7056447e9cc76ff0f2a9d5679b5ba27b96ab0e5c15ed759c4f"
                ],
                "nonce": "0x5",
                "max_fee": "0x0"
            }
        ],
        "simulation_flags": [
            "SKIP_VALIDATE",
            "SKIP_FEE_CHARGE"
        ]
    }
}`

**Comment by princearoragithub** [comment]
Does braavos handle simulation differently? This looks like length of calldata mismatch.
