### ISSUE TITLE
Price impact number looks incorrect.

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/jediswap-v2-interface#142]
### Description

I am not able to understand why the price impact is 99+% here

<img width="464" alt="image" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/4688513/7a314d3b-565a-4c44-a2b0-75aa10a3f1ef">

<img width="467" alt="image" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/4688513/9973c327-2e34-4d4a-98da-961956bb6174">

**Comment by vnaysngh-mudrex** [comment]
@rohitgoyal closing this
