### ISSUE TITLE
Increase visibility for hide side bar button 

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/jediswap-v2-interface#144]
### Description

Right now the user is facing difficulty figuring out how to close the wallet side bar.
 Rakesh need to update it in the design and then we need to implement the enhancement on the frontend.

**Comment by rohitgoyal** [comment]
Figma link
https://www.figma.com/file/UnuRGVIl2GLHyLSDGxajwp/JediSwap---Webapp-v2?type=design&node-id=1973-5267&mode=design&t=vI1jXNcqzy95ZLgk-4

**Comment by rohitgoyal** [comment]
@vnaysngh-mudrex Need to merge it to staging to test

**Comment by rohitgoyal** [comment]
@vnaysngh-mudrex reminder again for merging it

**Comment by iamoskvin** [comment]
> @vnaysngh-mudrex reminder again for merging it

I think we can close this issue. I did not know that we have this issue and the PR. So, I did the same and my code is already in the main.
