### ISSUE TITLE
Show USD value for tokens in swap page and LP page

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/jediswap-v2-interface#167]
### Description

We need to show USD value of tokens in the interface. 
For this we will need price API which we already have. @princearoragithub will share it

**Comment by vnaysngh-mudrex** [comment]
done and deployed on staging

**Comment by rohitgoyal** [comment]
@vnaysngh-mudrex
Right now we have USD value only for the input token. We need it for the output token as well with a % difference. Like in the below image from Uniswap.

![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/4688513/86b14629-17ca-48b7-bdc0-f93045ab2e9c)

Also same thing while adding liquidity.
![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/4688513/23509e52-09f4-4fc6-b95c-45ed11c2f3c6)

**Comment by rohitgoyal** [comment]
@vnaysngh-mudrex What is the status on this? 
I am confused where to test this

**Comment by vnaysngh-mudrex** [comment]
here https://deploy-preview-225--jade-otter-90f7ba.netlify.app/

**Comment by rohitgoyal** [comment]
I am testing on Sepolia. And I don't see the USD value anywhere.
<img width="554" alt="image" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/4688513/f688bdf6-0d51-4133-9965-f73b144174d7">

<img width="460" alt="image" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/4688513/f5bf925e-f244-4565-b910-660215bb2d1d">

**Comment by vnaysngh-mudrex** [comment]
it's deployed on prod, closing this
