### ISSUE TITLE
While adding liquidity to a pool where price is not initialised, price range inputs are not behaving correctly

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/jediswap-v2-interface#183]
### Description

https://www.loom.com/share/a66afebc6a784fc8878082b2bde6cd57

**Comment by vnaysngh-mudrex** [comment]
this is fixed and deployed to prod already

**Comment by rohitgoyal** [comment]
@vnaysngh-mudrex When i click on full range, click on low price which is input as 0 and click out side, the input changes to some random big number

**Comment by vnaysngh-mudrex** [comment]
will check this

**Comment by vnaysngh-mudrex** [comment]
@rohitgoyal this is fixed, closing this
