### ISSUE TITLE
Adding PFP using useStarkProfile

### ISSUE THREAD

**Issue by sdaav** [jediswaplabs/jediswap-v2-interface#194]
### Description 

Hello!

I see that stark domains are integrated into the super cool front-end template. It would be super cool to make the integration deeper by adding PFPs where it lacks using our documentation.

Based on each repo we will adapt the method used (check all methods https://docs.starknet.id/)

You have several choices: 
- Starknetid.js
- Starknet React
- Starknet.js
- API 

Up to you to choose the best method for each repository, the best will be to use the library you are already using! 

@Marchand-Nicolas, one of our team members, can help to do it if needed!

### Proposed to do

We would like to know if you can replace the wallet logo with the PFP, or if it's possible to keep both. Here's an integration proposal:

- [ ] PFP displayed after connecting wallet
<img width="421" alt="Capture d’écran 2024-03-25 à 16 33 16" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/57441909/e303942d-2b20-4ad6-87ed-f4bf7a78cfab">

- [ ] PFP displayed on this space
<img width="492" alt="Capture d’écran 2024-03-25 à 16 35 57" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/57441909/41a56890-7f8b-4996-8405-1bbb50bd52bb">

**Comment by Oshioke-Salaki** [comment]
Can i handle this?
