### ISSUE TITLE
Periodic, rare app crash on sepolia

### ISSUE THREAD

**Issue by iamoskvin** [jediswaplabs/jediswap-v2-interface#204]
### Description

![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/44796732/11e752ea-4abe-4ed4-aaa9-b2f8d53b336f)

**Comment by iamoskvin** [comment]
![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/44796732/faa3fe36-de3d-4905-89a6-dd6b1c806eec)
![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/44796732/61157b67-ec01-42c2-b81c-cc49cc08e33a)

**Comment by vnaysngh-mudrex** [comment]
It seems like a non-replicable issue on my end. I'm closing this for now. 
Feel free to open this if it becomes more frequent

**Comment by iamoskvin** [comment]
Steps to reproduce the issue:
Go to https://app.v2.staging.jediswap.xyz/#/pool
Connect to mainnet.
Then change the chain in the Argent wallet to the Sepolia and back to Maiinet quickly. You should get the error.
Try several times, pls.

**Comment by vnaysngh-mudrex** [comment]
it's a very low priority, and I'm still not able to reproduce. I am assigning this to you.

**Comment by iamoskvin** [comment]
Can't reproduce it on the latest app version.
