### ISSUE TITLE
Wrong min price calculation

### ISSUE THREAD

**Issue by iamoskvin** [jediswaplabs/jediswap-v2-interface#205]
### Description
Min price is set lower than the current price after clicking "full range". It was true for this pool that was initialized with a very low price.

![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/44796732/9385ff6e-76be-41c4-8284-7b83fb70add0)

**Comment by vnaysngh-mudrex** [comment]
this seems to be fixed, closing it
