### ISSUE TITLE
Max buts don't take into account second token balance

### ISSUE THREAD

**Issue by iamoskvin** [jediswaplabs/jediswap-v2-interface#220]
### Description

Also, we need to calculate amount that we needed for gas in case of ETH and STRK.
![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/44796732/f38e87d1-f359-4c0b-ad91-1a01659aa09b)

**Comment by vnaysngh-mudrex** [comment]
We never calculate the second token balance when you max out first. Instead, we should show an insufficient token balance. 

Also, about the gas calculation, its a feature and can be added to our board later.

@rohitgoyal

**Comment by iamoskvin** [comment]
> We never calculate the second token balance when you max out first. That's why we have two individual max buttons instead of one. Instead, we should show an insufficient token balance, and you have already created an issue for that.
> 
> Also, about the gas calculation, its a feature that can be added to our board later.
> 
> @rohitgoyal

1. Sure, we should show an insufficient token balance (as we do in v1). That is what I mean. And right now, don't do this and allow users to form incorrect TX that will fail due to insufficient balance.

2. I did not know that we had not made gas calculations before. Probably, it is not an important feature. I just used to have it in different dapps.
