### ISSUE TITLE
Unable to add out-of-range position: app crashing

### ISSUE THREAD

**Issue by iamoskvin** [jediswaplabs/jediswap-v2-interface#238]
### Description

![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/44796732/d7b2e46b-3cc5-4a84-84cf-49de60f6edd3)
After setting an STRK amount:
![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/44796732/0bf291d6-c9e1-4b48-8081-737c9756efc0)
![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/44796732/20cd2adb-2335-4fc5-ad9a-493709345519)

**Comment by rohitgoyal** [comment]
It is definitely not the out of range issue. I am able to add liquidity for out of range positions.

**Comment by iamoskvin** [comment]
> It is definitely not the out of range issue. I am able to add liquidity for out of range positions.

Try this one 
![image](https://github.com/jediswaplabs/jediswap-v2-interface/assets/44796732/a395d9a6-c08b-4247-a19c-2ffeb495919a)
