### ISSUE TITLE
Dashboard : List items should be fully clickable throughout

### ISSUE THREAD

**Issue by rakakar** [jediswaplabs/jediswap-v2-interface#294]
### Description

list items in Overview, Pools, Tokens page should be clickable throughout. Currently I can go inside pools/token from list by clicking on specifically the token/pool icons. Also add a hovered hilighted state to make the selection stand out (have added this is figma)

https://github.com/jediswaplabs/jediswap-v2-interface/assets/106336297/24282036-b445-4747-80f9-9829af4f3b9f

https://github.com/jediswaplabs/jediswap-v2-interface/assets/106336297/6fdf1dd3-3835-4001-af06-92c3ca0cd405

**Comment by iamoskvin** [comment]
fuxed
