### ISSUE TITLE
Fonts are not coming correctly in navigation bar

### ISSUE THREAD

**Issue by rohitgoyal** [jediswaplabs/jediswap-v2-interface#310]
### Description

In our web app, in the navigation, I don't see the correct font displaying. 
<img width="654" alt="image" src="https://github.com/jediswaplabs/jediswap-v2-interface/assets/4688513/c46e6d69-2d51-4c13-b1a0-4d0e44a1fe17">

I also see these two font related errors in the console. 

```
GET https://fonts.cdnfonts.com/css/avenir-lt-std net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin 403 (Forbidden)
app.jediswap.xyz/:1 

GET https://fonts.cdnfonts.com/css/soloist net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin 403 (Forbidden)

```

Device info:
Brave: v 1.64.122
Apple M2 MacBook Pro
Mac OS 13.2.1

**Comment by harshal2608** [comment]
@vnaysngh-mudrex both the fonts are not available on cdnfonts. Might have to host them on our end.

**Comment by harshal2608** [comment]
I have added black and light fonts right now. Couldnt find others in woff format. If someone could add them we wont need to rely on third party.
